### ISSUE TITLE
Escape tag content automatically?

### ISSUE THREAD

**Issue by jeanas** [asayers/html-builder#3]
Hi!

I recognize that I may have been making assumptions without good reason, but I was quite surprised to see that nodes don't escape any content that you write into them. From my point of view, it would make the library much more reliable. What do you think?

**Comment by asayers** [comment]
I agree - escaping text written into nodes sounds like the correct default.

**Comment by asayers** [comment]
Released v0.5, which includes escaping support:

* By default, text written into a `Node` is scanned for `&`, `<`, and `>`
* If you call `.raw()` on a node when you create it, it won't escape anything
* If you call `.safe()`, it'll escape `&`, `<`, `>`, `"`, `'`, and `/`

Please let me know if it works for you!

**Comment by jeanas** [comment]
Thanks!
